# Generated by Django 5.2.1 on 2025-05-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularsellerprofile',
            name='username',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
