# Generated by Django 5.2.1 on 2025-05-28 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholeSalerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=300)),
                ('shop_description', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('business_address', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user',)},
            },
        ),
        migrations.DeleteModel(
            name='WholeSellerProfile',
        ),
    ]
