# Generated by Django 5.2.1 on 2025-05-17 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_regularsellerprofile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularsellerprofile',
            old_name='username',
            new_name='nickname',
        ),
    ]
