# Generated by Django 5.2.1 on 2025-05-28 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_wholesalerprofile_delete_wholesellerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularsellerprofile',
            name='phone',
        ),
    ]
