# Generated by Django 5.2.1 on 2025-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_username_regularsellerprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularsellerprofile',
            name='nickname',
            field=models.CharField(default='maduagro', max_length=25, unique=True),
        ),
    ]
