# Generated by Django 5.2.1 on 2025-05-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_regularsellerprofile_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularsellerprofile',
            name='nickname',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
