# Generated by Django 5.2.1 on 2025-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_regularsellerprofile_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkbuyerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='regularbuyerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='regularsellerprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='wholesellerprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
