# Generated by Django 5.2.1 on 2025-06-12 00:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text="Customer's phone number", max_length=20, verbose_name='Phone Number')),
                ('email', models.EmailField(help_text="Customer's email address", max_length=254, verbose_name='Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Details',
                'verbose_name_plural': 'Contact Details',
            },
        ),
        migrations.CreateModel(
            name='ShippingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(db_index=True, max_length=255, verbose_name='Last Name')),
                ('street', models.CharField(blank=True, max_length=500, null=True, verbose_name='Street Address')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='City')),
                ('state', models.CharField(max_length=100, verbose_name='State/Province')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal Code')),
                ('country', models.CharField(db_index=True, max_length=100, verbose_name='Country')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default shipping address', verbose_name='Default Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, help_text='Unique order identifier', max_length=20, unique=True, verbose_name='Order Number')),
                ('product_name', models.CharField(help_text='Product name at time of order', max_length=200, verbose_name='Product Name')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Unit Price')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('PROCESSING', 'Processing'), ('PARTIALLY_SHIPPED', 'Partially Shipped'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20, verbose_name='Order Status')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total before shipping and fees', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Shipping Cost')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Platform Fee')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total Price')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Ordered At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('customer_notes', models.TextField(blank=True, help_text='Additional notes from customer', verbose_name='Customer Notes')),
                ('contact_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.contactdetails', verbose_name='Contact Details')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_orders', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('product', models.ForeignKey(help_text='Ordered product', on_delete=django.db.models.deletion.PROTECT, to='products.product', verbose_name='Product')),
                ('delivery_details', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.shippingdetails', verbose_name='Delivery Details')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-ordered_at'],
            },
        ),
        migrations.AddIndex(
            model_name='shippingdetails',
            index=models.Index(fields=['user', 'is_default'], name='orders_ship_user_id_4c2a69_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingdetails',
            index=models.Index(fields=['city', 'country'], name='orders_ship_city_e09685_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='orders_orde_custome_c9b64a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'ordered_at'], name='orders_orde_status_9cd221_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['ordered_at'], name='orders_orde_ordered_30150d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'),
        ),
    ]
