# Generated by Django 5.2.1 on 2025-06-12 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_completed_orderitem_delivery_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='platform_fee',
        ),
    ]
