# Generated by Django 5.2.1 on 2025-06-12 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_platform_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernote',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='ordernote',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='orders.orderitem'),
        ),
    ]
