# Generated by Django 5.2.1 on 2025-05-26 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_quantity_product_available_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.CharField(choices=[('available', 'Available'), ('low', 'Low in Stock'), ('out', 'Out of Stock')], default='out', max_length=10),
        ),
    ]
