# Generated by Django 5.2.1 on 2025-05-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='available',
            new_name='availability_status',
        ),
    ]
