# Generated by Django 5.2.1 on 2025-05-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_available_product_availability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight_per_unit',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
